import './global.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'M-M de suejes',
  description: 'Generated by create next app',
  authors: [
    { name: "Ricardo Basurto" },
    { name: "Eiichi Matsuo" },
    { name: "RPM Code", url: "https://www.rpmspeedcode.com/" },
  ],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>{children}</body>
    </html>
  )
}
